from __future__ import annotations

import asyncio
import os
import time

import cv2
from contextlib import asynccontextmanager

# CPU oversubscription guard: camera/inference workers are already threaded.
# Keep each native math backend from spawning a second large thread pool.
try:
    import cv2
    import torch
    _native_threads = int(os.getenv("KAVRON_CPU_THREADS", "0"))
    if _native_threads <= 0:
        _native_threads = max(1, min(4, (os.cpu_count() or 4) // 2))
    cv2.setNumThreads(_native_threads)
    torch.set_num_threads(_native_threads)
    try:
        torch.set_num_interop_threads(max(1, min(2, _native_threads)))
    except Exception:
        pass
except Exception:
    pass

from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware

from app.core.config import get_settings
from app.core.bus import EventBus
from app.core.state import RuntimeState

from app.database.db import init_db
from app.database.db import SessionLocal

from app.api.routes import router

# NEW: anomaly / intrusion API
from app.api.anomaly_routes import router as anomaly_router
from app.api.stage4_routes import router as stage4_router
from app.api.map_routes import router as map_router
from app.api.stage5_routes import router as stage5_router

from app.ai.registry import ModelRegistry
from app.ai.scheduler import InferenceScheduler
from app.ai.model_manager import ModelAssetManager

from app.camera.registry import CameraRegistry
from app.events.engine import EventEngine


# ============================================================
# SETTINGS
# ============================================================

settings = get_settings()


# ============================================================
# EVENT HANDLER
# ============================================================

def _handle_event(
    event,
    events,
    bus,
    loop,
):
    """
    Handle events generated by the AI pipeline.

    Detection events are passed to the EventEngine.
    Every event is also published to the EventBus so that
    the WebSocket clients can receive it in real time.
    """

    try:
        if event.get("type") == "detection":
            asyncio.run_coroutine_threadsafe(
                events.handle_detection(event),
                loop,
            )

        asyncio.run_coroutine_threadsafe(
            bus.publish(event),
            loop,
        )

    except Exception as exc:
        print(
            f"[KAVRON] Event handler error: {exc}"
        )


# ============================================================
# APPLICATION LIFESPAN
# ============================================================

@asynccontextmanager
async def lifespan(app: FastAPI):

    settings = get_settings()

    # --------------------------------------------------------
    # Initialize database
    # --------------------------------------------------------

    print(
        "[KAVRON] Initializing database..."
    )

    init_db()

    print(
        "[KAVRON] Database initialization complete."
    )

    # --------------------------------------------------------
    # Runtime state + event bus
    # --------------------------------------------------------

    state = RuntimeState()

    bus = EventBus()

    loop = asyncio.get_running_loop()

    # --------------------------------------------------------
    # AI model registry
    # --------------------------------------------------------

    print(
        "[KAVRON] Initializing AI model registry..."
    )

    registry = ModelRegistry(
        settings.model_dir,
        settings.device,
    )

    # --------------------------------------------------------
    # Camera state callback
    # --------------------------------------------------------

    def camera_callback(s):

        try:

            state.set_camera(
                s.camera_id,
                s.__dict__.copy(),
            )

            asyncio.run_coroutine_threadsafe(
                bus.publish(
                    {
                        "type": "camera_state",
                        **s.__dict__,
                    }
                ),
                loop,
            )

        except Exception as exc:

            print(
                "[KAVRON] Camera callback error: "
                f"{exc}"
            )

    # --------------------------------------------------------
    # Frame callback
    # --------------------------------------------------------

    jpeg_last_encoded: dict[str, float] = {}

    def on_frame(packet):

        try:

            state.set_frame(packet.camera_id, packet.frame)
            # Encode at a bounded UI-stream cadence instead of paying JPEG cost
            # for every captured frame. AI inference remains independently paced.
            now = time.monotonic()
            jpeg_interval = 1.0 / max(1.0, settings.stream_jpeg_fps)
            if now - jpeg_last_encoded.get(packet.camera_id, 0.0) >= jpeg_interval:
                ok, buffer = cv2.imencode(".jpg", packet.frame, [int(cv2.IMWRITE_JPEG_QUALITY), 68])
                if ok:
                    state.set_jpeg(packet.camera_id, buffer.tobytes())
                    jpeg_last_encoded[packet.camera_id] = now
            scheduler.submit(packet)

        except Exception as exc:

            print(
                "[KAVRON] Frame callback error: "
                f"{exc}"
            )

    # --------------------------------------------------------
    # Camera registry
    # --------------------------------------------------------

    cams = CameraRegistry(
        on_frame,
        camera_callback,
        settings.max_queue_size,
    )

    # --------------------------------------------------------
    # Event engine
    # --------------------------------------------------------

    async def publish(event):

        await bus.publish(event)

    events = EventEngine(
        state,
        publish,
    )

    # --------------------------------------------------------
    # AI inference scheduler
    # --------------------------------------------------------

    scheduler = InferenceScheduler(
        settings,
        cams,
        state,
        lambda event: _handle_event(
            event,
            events,
            bus,
            loop,
        ),
    )

    scheduler.attach_registry(
        registry
    )

    # --------------------------------------------------------
    # Store runtime services on FastAPI app.state
    # --------------------------------------------------------

    app.state.settings = settings

    app.state.runtime_state = state

    app.state.event_bus = bus

    app.state.model_registry = registry

    app.state.camera_registry = cams

    app.state.event_engine = events

    app.state.scheduler = scheduler
    app.state.model_asset_manager = ModelAssetManager(settings.model_dir)

    # Stage 3 specialist weights are large and optional, so download them in a
    # daemon thread. The API remains responsive while the model pack is fetched.
    if settings.stage3_enabled and settings.auto_download_specialist_models:
        import threading

        def _download_specialists():
            manager = app.state.model_asset_manager
            for key in ("face_detector", "face_recognizer", "plate_detector"):
                try:
                    manager.ensure(key)
                    print(f"[KAVRON] Stage 3 model ready: {key}")
                except Exception as exc:
                    print(f"[KAVRON] Stage 3 model download warning ({key}): {exc}")

        threading.Thread(target=_download_specialists, name="kavron-model-bootstrap", daemon=True).start()

    # ========================================================
    # AUTO-DISCOVER ALL VIDEO FILES
    # ========================================================

    data_dir = os.path.dirname(
        settings.demo_video
    )

    supported_video_extensions = {
        ".mp4",
        ".avi",
        ".mov",
        ".mkv",
        ".webm",
        ".m4v",
    }

    video_files: list[str] = []

    if os.path.isdir(data_dir):

        for filename in sorted(
            os.listdir(data_dir)
        ):

            full_path = os.path.join(
                data_dir,
                filename,
            )

            if not os.path.isfile(full_path):
                continue

            extension = os.path.splitext(
                filename
            )[1].lower()

            if extension in supported_video_extensions:

                video_files.append(
                    full_path
                )

    # --------------------------------------------------------
    # Keep configured demo video first
    # --------------------------------------------------------

    if os.path.isfile(
        settings.demo_video
    ):

        configured_demo = os.path.normcase(
            os.path.abspath(
                settings.demo_video
            )
        )

        normalized_videos = {
            os.path.normcase(
                os.path.abspath(path)
            )
            for path in video_files
        }

        if configured_demo in normalized_videos:

            video_files = [
                settings.demo_video,
                *[
                    path
                    for path in video_files
                    if (
                        os.path.normcase(
                            os.path.abspath(
                                path
                            )
                        )
                        != configured_demo
                    )
                ],
            ]

        else:

            video_files.insert(
                0,
                settings.demo_video,
            )

    # --------------------------------------------------------
    # Remove duplicates
    # --------------------------------------------------------

    deduped_video_files: list[str] = []

    seen_video_paths: set[str] = set()

    for path in video_files:

        key = os.path.normcase(
            os.path.abspath(path)
        )

        if key not in seen_video_paths:

            seen_video_paths.add(key)

            deduped_video_files.append(
                path
            )

    video_files = deduped_video_files

    from app.database.repositories import CameraRepo

    # Remove stale auto-discovered demo cameras from earlier package versions.
    # Manually created/live cameras are left untouched.
    expected_demo_ids = {f"CAM-DEMO-{i:02d}" for i in range(1, len(video_files) + 1)}
    try:
        with SessionLocal() as cleanup_session:
            for existing in CameraRepo.list(cleanup_session):
                if existing.id.startswith("CAM-DEMO-") and existing.id not in expected_demo_ids:
                    cleanup_session.delete(existing)
            cleanup_session.commit()
    except Exception as exc:
        print(f"[KAVRON] Demo camera cleanup warning: {exc}")

    # ========================================================
    # CAMERA PERSISTENCE
    # ========================================================

    # ========================================================
    # REGISTER ALL DISCOVERED VIDEOS
    # ========================================================

    for index, video_path in enumerate(
        video_files,
        start=1,
    ):

        camera_id = (
            f"CAM-DEMO-{index:02d}"
        )

        camera_name = (
            f"Demo Camera {index:02d}"
        )

        demo_camera = {
            "camera_id": camera_id,
            "name": camera_name,
            "source": video_path,
            "protocol": "file",
            "location": (
                "Demo Sector"
                if index == 1
                else f"Demo Sector {index:02d}"
            ),
            "sector": (
                "DEMO"
                if index == 1
                else f"DEMO-{index:02d}"
            ),
        }

        print(
            "[KAVRON] Registering video: "
            f"{camera_id} -> {video_path}"
        )

        # ----------------------------------------------------
        # Add camera to runtime registry
        # ----------------------------------------------------

        try:

            cams.add(
                demo_camera
            )

        except Exception as exc:

            print(
                "[KAVRON] Warning: could not "
                f"register {camera_id}: {exc}"
            )

            continue

        # ----------------------------------------------------
        # Save initial runtime state
        # ----------------------------------------------------

        if camera_id in cams.items:

            state.set_camera(
                camera_id,
                cams.items[
                    camera_id
                ].__dict__.copy(),
            )

        # ----------------------------------------------------
        # Persist camera in SQLite
        # ----------------------------------------------------

        session = None

        try:

            session = SessionLocal()

            CameraRepo.upsert(
                session,
                {
                    "id": camera_id,
                    "name": camera_name,
                    "source": video_path,
                    "protocol": "file",
                    "location": (
                        demo_camera[
                            "location"
                        ]
                    ),
                    "sector": (
                        demo_camera[
                            "sector"
                        ]
                    ),
                    "enabled": True,
                },
            )

            session.commit()

        except Exception as exc:

            print(
                "[KAVRON] Warning: could not "
                f"persist {camera_id}: {exc}"
            )

            if session is not None:

                try:
                    session.rollback()

                except Exception:
                    pass

        finally:

            if session is not None:

                try:
                    session.close()

                except Exception:
                    pass

        # ----------------------------------------------------
        # Refresh runtime state
        # ----------------------------------------------------

        if camera_id in cams.items:

            state.set_camera(
                camera_id,
                cams.items[
                    camera_id
                ].__dict__.copy(),
            )

    # ========================================================
    # LOAD VIRTUAL FENCES INTO THE EVENT ENGINE
    # ========================================================

    try:
        from app.database.repositories import FenceRepo
        with SessionLocal() as fence_session:
            events.set_fences([
                {
                    column.name: getattr(item, column.name)
                    for column in item.__table__.columns
                }
                for item in FenceRepo.list(fence_session)
            ])
    except Exception as exc:
        print(f"[KAVRON] Fence bootstrap warning: {exc}")

    # ========================================================
    # START INFERENCE SCHEDULER
    # ========================================================

    print(
        "[KAVRON] Starting inference scheduler..."
    )

    scheduler.start()

    # ========================================================
    # AUTO-START VIDEO CAMERAS
    # ========================================================

    if (
        os.getenv(
            "KAVRON_AUTOSTART_DEMO",
            "1",
        )
        == "1"
    ):

        for camera_id in list(
            cams.items.keys()
        ):

            try:

                cams.start(
                    camera_id
                )

                print(
                    "[KAVRON] Demo camera "
                    f"started: {camera_id}"
                )

            except Exception as exc:

                print(
                    "[KAVRON] Warning: "
                    f"could not start "
                    f"{camera_id}: {exc}"
                )

    # ========================================================
    # APPLICATION READY
    # ========================================================

    print(
        "[KAVRON] Intelligence backend initialized."
    )

    print(
        "[KAVRON] Models directory: "
        f"{settings.model_dir}"
    )

    print(
        "[KAVRON] Device: "
        f"{settings.device}"
    )

    print(
        "[KAVRON] Demo video: "
        f"{settings.demo_video}"
    )

    print(
        "[KAVRON] Video sources discovered: "
        f"{len(video_files)}"
    )

    print(
        "[KAVRON] Cameras registered: "
        f"{list(cams.items.keys())}"
    )

    print(
        "[KAVRON] Anomaly API enabled."
    )

    yield

    # ========================================================
    # GRACEFUL SHUTDOWN
    # ========================================================

    print(
        "[KAVRON] Shutting down..."
    )

    try:

        scheduler.stop()

    except Exception as exc:

        print(
            "[KAVRON] Scheduler shutdown "
            f"warning: {exc}"
        )

    try:

        cams.stop_all()

    except Exception as exc:

        print(
            "[KAVRON] Camera shutdown "
            f"warning: {exc}"
        )

    print(
        "[KAVRON] Shutdown complete."
    )


# ============================================================
# FASTAPI APPLICATION
# ============================================================

app = FastAPI(
    title="KAVRON Intelligence API",
    version=settings.version,
    description=(
        "Real-time AI visual security backend"
    ),
    lifespan=lifespan,
)


# ============================================================
# WEBSOCKET EVENTS
# ============================================================

@app.websocket("/ws/events")
async def websocket_events(
    websocket: WebSocket,
):
    """
    Real-time KAVRON event stream.

    Frontend clients can connect to:
        ws://127.0.0.1:8000/ws/events
    """

    await websocket.accept()

    print(
        "[KAVRON] WebSocket client connected"
    )

    bus: EventBus = (
        websocket.app.state.event_bus
    )

    queue = await bus.subscribe(
        "*"
    )

    try:

        while True:

            event = await queue.get()

            await websocket.send_json(
                event
            )

    except WebSocketDisconnect:

        print(
            "[KAVRON] WebSocket client "
            "disconnected"
        )

    except Exception as exc:

        print(
            "[KAVRON] WebSocket error: "
            f"{exc}"
        )

    finally:

        try:

            await bus.unsubscribe(
                "*",
                queue,
            )

        except Exception as exc:

            print(
                "[KAVRON] WebSocket cleanup "
                f"warning: {exc}"
            )


# ============================================================
# CORS CONFIGURATION
# ============================================================

ALLOWED_ORIGINS = [
    "http://localhost:8443",
    "http://127.0.0.1:8443",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]


try:

    configured_origins = (
        settings.origins
    )

    if isinstance(
        configured_origins,
        str,
    ):

        configured_origins = [
            origin.strip()
            for origin
            in configured_origins.split(",")
            if origin.strip()
        ]

    for origin in (
        configured_origins or []
    ):

        if (
            origin
            not in ALLOWED_ORIGINS
        ):

            ALLOWED_ORIGINS.append(
                origin
            )

except Exception as exc:

    print(
        "[KAVRON] Warning reading "
        f"configured CORS origins: {exc}"
    )


# ============================================================
# CORS MIDDLEWARE
# ============================================================

@app.middleware("http")
async def location_permissions(request, call_next):
    response = await call_next(request)
    response.headers["Permissions-Policy"] = "geolocation=(self)"
    return response


app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=[
        "GET",
        "POST",
        "PUT",
        "PATCH",
        "DELETE",
        "OPTIONS",
    ],
    allow_headers=["*"],
)


# ============================================================
# API ROUTES
# ============================================================

# Existing KAVRON routes
app.include_router(
    router,
    prefix="/api/v1",
)


# NEW:
# Intrusion / anomaly routes
#
# Examples:
#
# GET
# /api/v1/anomalies
#
# GET
# /api/v1/anomalies/{anomaly_id}
#
# PATCH
# /api/v1/anomalies/{anomaly_id}/acknowledge
#
app.include_router(
    anomaly_router,
    prefix="/api/v1",
)

app.include_router(
    stage4_router,
    prefix="/api/v1",
)

app.include_router(
    map_router,
    prefix="/api/v1",
)

app.include_router(
    stage5_router,
    prefix="/api/v1",
)


# ============================================================
# ROOT ENDPOINT
# ============================================================

@app.get("/")
def root():

    return {
        "name": "KAVRON",
        "description": (
            "Intelligent Visual Security Platform"
        ),
        "docs": "/docs",
        "api": "/api/v1",
        "websocket": "/ws/events",
        "anomalies": "/api/v1/anomalies",
    }